"""Default configuration for BitBirch clustering."""

# Fingerprint defaults
FINGERPRINT_TYPE = "ECFP4"
N_BITS = 2048

# BitBirch clustering defaults
THRESHOLD = 0.3
BRANCHING_FACTOR = 10_000
MERGE_CRITERION = "diameter"

# Reclustering defaults
RECLUSTERING_ITERATIONS_INITIAL = 3
RECLUSTERING_ITERATIONS_MIDSECTION = 0
RECLUSTERING_ITERATIONS_FINAL = 0
RECLUSTERING_EXTRA_THRESHOLD = 0.025

# Midsection round defaults
MIDSECTION_THRESHOLD_CHANGE = 0.0
NUM_MIDSECTION_ROUNDS = 5
BIN_SIZE = 5

# SLURM defaults
SLURM_MEM_INITIAL = "16G"
SLURM_CPUS_INITIAL = 1
SLURM_MEM_MIDSECTION = "48G"
SLURM_CPUS_MIDSECTION = 3
SLURM_MEM_FINAL = "96G"
SLURM_CPUS_FINAL = 6
SLURM_TIME = "24:00:00"
SLURM_PARTITION = ""

# HPC defaults
FILES_PER_JOB = 10
